clear @a[tag=game_player,tag=!EVENT_GP_GameBegin.is_close_to_portal,tag=EVENT_GP_GameBegin.in_hobby] ender_eye
execute if score EVENT_GP_GameBegin_Portal_EnderEye counter matches 0 run replaceitem entity @a[tag=game_player,tag=EVENT_GP_GameBegin.is_close_to_portal] slot.hotbar 4 ender_eye 12 0 {"can_place_on":{"blocks":["end_portal_frame"]},"item_lock":{"mode":"lock_in_slot"}}
execute if score EVENT_GP_GameBegin_Portal_EnderEye counter matches 1 run replaceitem entity @a[tag=game_player,tag=EVENT_GP_GameBegin.is_close_to_portal] slot.hotbar 4 ender_eye 11 0 {"can_place_on":{"blocks":["end_portal_frame"]},"item_lock":{"mode":"lock_in_slot"}}
execute if score EVENT_GP_GameBegin_Portal_EnderEye counter matches 2 run replaceitem entity @a[tag=game_player,tag=EVENT_GP_GameBegin.is_close_to_portal] slot.hotbar 4 ender_eye 10 0 {"can_place_on":{"blocks":["end_portal_frame"]},"item_lock":{"mode":"lock_in_slot"}}
execute if score EVENT_GP_GameBegin_Portal_EnderEye counter matches 3 run replaceitem entity @a[tag=game_player,tag=EVENT_GP_GameBegin.is_close_to_portal] slot.hotbar 4 ender_eye 9 0 {"can_place_on":{"blocks":["end_portal_frame"]},"item_lock":{"mode":"lock_in_slot"}}
execute if score EVENT_GP_GameBegin_Portal_EnderEye counter matches 4 run replaceitem entity @a[tag=game_player,tag=EVENT_GP_GameBegin.is_close_to_portal] slot.hotbar 4 ender_eye 8 0 {"can_place_on":{"blocks":["end_portal_frame"]},"item_lock":{"mode":"lock_in_slot"}}
execute if score EVENT_GP_GameBegin_Portal_EnderEye counter matches 5 run replaceitem entity @a[tag=game_player,tag=EVENT_GP_GameBegin.is_close_to_portal] slot.hotbar 4 ender_eye 7 0 {"can_place_on":{"blocks":["end_portal_frame"]},"item_lock":{"mode":"lock_in_slot"}}
execute if score EVENT_GP_GameBegin_Portal_EnderEye counter matches 6 run replaceitem entity @a[tag=game_player,tag=EVENT_GP_GameBegin.is_close_to_portal] slot.hotbar 4 ender_eye 6 0 {"can_place_on":{"blocks":["end_portal_frame"]},"item_lock":{"mode":"lock_in_slot"}}
execute if score EVENT_GP_GameBegin_Portal_EnderEye counter matches 7 run replaceitem entity @a[tag=game_player,tag=EVENT_GP_GameBegin.is_close_to_portal] slot.hotbar 4 ender_eye 5 0 {"can_place_on":{"blocks":["end_portal_frame"]},"item_lock":{"mode":"lock_in_slot"}}
execute if score EVENT_GP_GameBegin_Portal_EnderEye counter matches 8 run replaceitem entity @a[tag=game_player,tag=EVENT_GP_GameBegin.is_close_to_portal] slot.hotbar 4 ender_eye 4 0 {"can_place_on":{"blocks":["end_portal_frame"]},"item_lock":{"mode":"lock_in_slot"}}
execute if score EVENT_GP_GameBegin_Portal_EnderEye counter matches 9 run replaceitem entity @a[tag=game_player,tag=EVENT_GP_GameBegin.is_close_to_portal] slot.hotbar 4 ender_eye 3 0 {"can_place_on":{"blocks":["end_portal_frame"]},"item_lock":{"mode":"lock_in_slot"}}
execute if score EVENT_GP_GameBegin_Portal_EnderEye counter matches 10 run replaceitem entity @a[tag=game_player,tag=EVENT_GP_GameBegin.is_close_to_portal] slot.hotbar 4 ender_eye 2 0 {"can_place_on":{"blocks":["end_portal_frame"]},"item_lock":{"mode":"lock_in_slot"}}
execute if score EVENT_GP_GameBegin_Portal_EnderEye counter matches 11 run replaceitem entity @a[tag=game_player,tag=EVENT_GP_GameBegin.is_close_to_portal] slot.hotbar 4 ender_eye 1 0 {"can_place_on":{"blocks":["end_portal_frame"]},"item_lock":{"mode":"lock_in_slot"}}
execute if score EVENT_GP_GameBegin_Portal_EnderEye counter matches 12 run replaceitem entity @a[tag=game_player,tag=EVENT_GP_GameBegin.is_close_to_portal] slot.hotbar 4 air