scoreboard players add EVENT_CW_AbandonedTransport_Area9_Battle1 timer 1

execute if score EVENT_CW_AbandonedTransport_Area9_Battle1_EnemyAmount counter matches 0 if score EVENT_CW_AbandonedTransport_Area9_Battle1_WaveCountdown timer matches 0.. run scoreboard players add EVENT_CW_AbandonedTransport_Area9_Battle1_WaveCountdown timer -1