execute if score @s arctan_input matches 0 run scoreboard players set @s arctan_output 0
execute if score @s arctan_input matches 1 run scoreboard players set @s arctan_output 6
execute if score @s arctan_input matches 2 run scoreboard players set @s arctan_output 11
execute if score @s arctan_input matches 3 run scoreboard players set @s arctan_output 17
execute if score @s arctan_input matches 4 run scoreboard players set @s arctan_output 22
execute if score @s arctan_input matches 5 run scoreboard players set @s arctan_output 27
execute if score @s arctan_input matches 6 run scoreboard players set @s arctan_output 31
execute if score @s arctan_input matches 7 run scoreboard players set @s arctan_output 35
execute if score @s arctan_input matches 8 run scoreboard players set @s arctan_output 39
execute if score @s arctan_input matches 9 run scoreboard players set @s arctan_output 42
execute if score @s arctan_input matches 10 run scoreboard players set @s arctan_output 45
execute if score @s arctan_input matches 11 run scoreboard players set @s arctan_output 48
execute if score @s arctan_input matches 12 run scoreboard players set @s arctan_output 50
execute if score @s arctan_input matches 13 run scoreboard players set @s arctan_output 52
execute if score @s arctan_input matches 14 run scoreboard players set @s arctan_output 54
execute if score @s arctan_input matches 15 run scoreboard players set @s arctan_output 56
execute if score @s arctan_input matches 16 run scoreboard players set @s arctan_output 58
execute if score @s arctan_input matches 17 run scoreboard players set @s arctan_output 60
execute if score @s arctan_input matches 18 run scoreboard players set @s arctan_output 61
execute if score @s arctan_input matches 19 run scoreboard players set @s arctan_output 62
execute if score @s arctan_input matches 20 run scoreboard players set @s arctan_output 63
execute if score @s arctan_input matches 21 run scoreboard players set @s arctan_output 65
execute if score @s arctan_input matches 22 run scoreboard players set @s arctan_output 65
execute if score @s arctan_input matches 23 run scoreboard players set @s arctan_output 66
execute if score @s arctan_input matches 24 run scoreboard players set @s arctan_output 67
execute if score @s arctan_input matches 25 run scoreboard players set @s arctan_output 68
execute if score @s arctan_input matches 26 run scoreboard players set @s arctan_output 69
execute if score @s arctan_input matches 27 run scoreboard players set @s arctan_output 69
execute if score @s arctan_input matches 28 run scoreboard players set @s arctan_output 70
execute if score @s arctan_input matches 29 run scoreboard players set @s arctan_output 71
execute if score @s arctan_input matches 30 run scoreboard players set @s arctan_output 72
execute if score @s arctan_input matches 31 run scoreboard players set @s arctan_output 72
execute if score @s arctan_input matches 32 run scoreboard players set @s arctan_output 73
execute if score @s arctan_input matches 33 run scoreboard players set @s arctan_output 73
execute if score @s arctan_input matches 34 run scoreboard players set @s arctan_output 74
execute if score @s arctan_input matches 35 run scoreboard players set @s arctan_output 74
execute if score @s arctan_input matches 36 run scoreboard players set @s arctan_output 74
execute if score @s arctan_input matches 37 run scoreboard players set @s arctan_output 75
execute if score @s arctan_input matches 38 run scoreboard players set @s arctan_output 75
execute if score @s arctan_input matches 39 run scoreboard players set @s arctan_output 76
execute if score @s arctan_input matches 40 run scoreboard players set @s arctan_output 76
execute if score @s arctan_input matches 41 run scoreboard players set @s arctan_output 76
execute if score @s arctan_input matches 42 run scoreboard players set @s arctan_output 77
execute if score @s arctan_input matches 43 run scoreboard players set @s arctan_output 77
execute if score @s arctan_input matches 44 run scoreboard players set @s arctan_output 77
execute if score @s arctan_input matches 45 run scoreboard players set @s arctan_output 77
execute if score @s arctan_input matches 46 run scoreboard players set @s arctan_output 78
execute if score @s arctan_input matches 47 run scoreboard players set @s arctan_output 78
execute if score @s arctan_input matches 48 run scoreboard players set @s arctan_output 78
execute if score @s arctan_input matches 49 run scoreboard players set @s arctan_output 78
execute if score @s arctan_input matches 50 run scoreboard players set @s arctan_output 79
execute if score @s arctan_input matches 51 run scoreboard players set @s arctan_output 79
execute if score @s arctan_input matches 52 run scoreboard players set @s arctan_output 79
execute if score @s arctan_input matches 53 run scoreboard players set @s arctan_output 79
execute if score @s arctan_input matches 54 run scoreboard players set @s arctan_output 80
execute if score @s arctan_input matches 55 run scoreboard players set @s arctan_output 80
execute if score @s arctan_input matches 56 run scoreboard players set @s arctan_output 80
execute if score @s arctan_input matches 57 run scoreboard players set @s arctan_output 80
execute if score @s arctan_input matches 58 run scoreboard players set @s arctan_output 80
execute if score @s arctan_input matches 59 run scoreboard players set @s arctan_output 80
execute if score @s arctan_input matches 60 run scoreboard players set @s arctan_output 81
execute if score @s arctan_input matches 61 run scoreboard players set @s arctan_output 81
execute if score @s arctan_input matches 62 run scoreboard players set @s arctan_output 81
execute if score @s arctan_input matches 63.. run scoreboard players set @s arctan_output 81